print("-----------------------------")
print("Fill your data with 1 and up.")
print("-----------------------------")
s = int(input("Input Your Distance(km) : "))
t = int(input("Input Your Time(hr) : "))
print("-----------------------------")
v = int(s/t)
print("Speed(v) is",v,"km/hr")
print("-----------------------------")
